POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxIiwiaWQiOiI2OTBjZWU1YWRkMDBlOWM5MTM2Nzg5NjAiLCJpYXQiOjE3NjI0NTU0ODZ9.Z92_fPTGbb5kpZttS3ieX_AsYTpukevdHnXAdVeRfsw

  {
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "userId": "690ced3e034f4c0d33fff921"
  }