POST http://localhost:3003/api/blogs
Content-Type: application/json

  {
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "userId": "690ced3e034f4c0d33fff921"
  }